version: "3.8"

volumes:
  mongodata:

networks:
  prodcon_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - prodcon_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - prodcon_network

  producer:
    image: ACR_PLACEHOLDER/producer:latest
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - prodcon_network

  consumer_health_check:
    image: ACR_PLACEHOLDER/consumer_health_check:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network
    healthcheck:
      test: curl --silent --fail http://consumer_health_check:5000/health_check || exit 1
      interval: 30s
      retries: 3

  consumer_insert_record:
    image: ACR_PLACEHOLDER/consumer_insert_record:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=database
      - MONGO_COLLECTION=ccdb
    networks:
      - prodcon_network
    healthcheck:
      test: curl --silent --fail http://consumer_insert_record:5000/insert_record || exit 1
      interval: 30s
      retries: 3

  consumer_delete_record:
    image: ACR_PLACEHOLDER/consumer_delete_record:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=database
      - MONGO_COLLECTION=ccdb
    networks:
      - prodcon_network
    healthcheck:
      test: curl --silent --fail http://consumer_delete_record:5000/delete_record || exit 1
      interval: 30s
      retries: 3

  consumer_read_database:
    image: ACR_PLACEHOLDER/consumer_read_database:latest
    command: python3 read_database.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=database
      - MONGO_COLLECTION=ccdb
    networks:
      - prodcon_network
    healthcheck:
      test: curl --silent --fail http://consumer_read_database:5000/read_database || exit 1
      interval: 30s
      retries: 3
