version: "3.8"

volumes:
  mongodata:

networks:
  prodcon_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - prodcon_network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    logging:
      driver: none
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - prodcon_network

  producer:
    build: Producer/
    image: 872515253964.dkr.ecr.eu-west-2.amazonaws.com/microservice-communication:producer
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - prodcon_network

  consumer_health_check:
    build: Consumer_one/
    image: 872515253964.dkr.ecr.eu-west-2.amazonaws.com/microservice-communication:consumer_health_check
    depends_on:
      producer:
        condition: service_started
    networks:
      - prodcon_network

  consumer_insert_record:
    build: Consumer_two/
    image: 872515253964.dkr.ecr.eu-west-2.amazonaws.com/microservice-communication:consumer_insert_record
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network

  consumer_delete_record:
    build: Consumer_three/
    image: 872515253964.dkr.ecr.eu-west-2.amazonaws.com/microservice-communication:consumer_delete_record
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network

  consumer_read_database:
    build: Consumer_four/
    image: 872515253964.dkr.ecr.eu-west-2.amazonaws.com/microservice-communication:consumer_read_database
    command: python3 read_database.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - prodcon_network
